# Generated by Django 5.2.15 on 2026-06-04 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stadium',
            name='name_es',
            field=models.CharField(blank=True, help_text='Nombre para mostrar, en español.', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='stage',
            name='key',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='team',
            name='confederation',
            field=models.CharField(choices=[('UEFA', 'UEFA'), ('CONMEBOL', 'CONMEBOL'), ('CONCACAF', 'CONCACAF'), ('CAF', 'África'), ('AFC', 'Asía'), ('OFC', 'Oceanía')], max_length=10),
        ),
    ]
