# Generated by Django 5.2.15 on 2026-06-04 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0002_stadium_name_es_alter_stage_key_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stage',
            name='confirm_deadline',
        ),
        migrations.AddField(
            model_name='stage',
            name='send_deadline',
            field=models.DateTimeField(blank=True, help_text='Límite para enviar (UTC). Al vencer: auto-envía lo guardado.', null=True),
        ),
    ]
