# Generated by Django 5.2.15 on 2026-06-04 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0003_remove_stage_confirm_deadline_stage_send_deadline'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='code',
            field=models.CharField(blank=True, help_text='Token del ganador, traza el bracket (p. ej. "W74").', max_length=10),
        ),
        migrations.AddField(
            model_name='match',
            name='name',
            field=models.CharField(blank=True, help_text='Etiqueta legible (p. ej. "Cuartos 3", "Final").', max_length=40),
        ),
    ]
