# Generated by Django 5.2.15 on 2026-06-04 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0004_match_code_match_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='match',
            name='code',
        ),
        migrations.AddField(
            model_name='team',
            name='flag_code',
            field=models.CharField(blank=True, help_text="ISO alpha-2 del PNG local (ej. 'mx'; 'gb-eng' para ENG).", max_length=6),
        ),
        migrations.AlterField(
            model_name='match',
            name='away_placeholder',
            field=models.CharField(blank=True, help_text='Origen textual del equipo visitante (p. ej. "1B", "W75").', max_length=20),
        ),
    ]
