# Generated by Django 5.2.15 on 2026-06-18 00:17

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0005_remove_match_code_team_flag_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stage',
            name='is_group',
            field=models.BooleanField(default=False, help_text='True en las 3 jornadas de grupos; la UI las colapsa en una sola pestaña.'),
        ),
        migrations.AddField(
            model_name='stage',
            name='multiplier',
            field=models.DecimalField(decimal_places=1, default=Decimal('1.0'), help_text='Ponderador de la fase: los puntos se multiplican por este factor (1, 1.5, 2 … hasta 10). Aún no aplicado.', max_digits=3),
        ),
    ]
