# Generated by Django 5.2.15 on 2026-06-26 04:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0006_stage_is_group_stage_multiplier'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stage',
            name='multiplier',
        ),
    ]
