# Generated by Django 5.2.15 on 2026-06-04 19:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pool', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stageuser',
            name='closed_at',
        ),
    ]
