# Generated by Django 5.2.15 on 2026-06-05 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pool', '0002_remove_stageuser_closed_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
