# Generated by Django 5.2.15 on 2026-06-11 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pool', '0003_alter_user_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_virtual',
            field=models.BooleanField(default=False, help_text='Perfil agregado (Ignorancia colectiva): visible, sin login y fuera de premios.'),
        ),
    ]
