# Generated by Django 5.2.15 on 2026-06-25 20:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pool', '0008_quiniela_rule_prediction_base_points_and_more'),
        ('tournament', '0006_stage_is_group_stage_multiplier'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserQuiniela',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('authorized', models.BooleanField(default=False, help_text='Pagó y envió a tiempo; se marca a mano.')),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'membresía de quiniela',
                'verbose_name_plural': 'membresías de quiniela',
            },
        ),
        migrations.CreateModel(
            name='Window',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveSmallIntegerField()),
                ('name', models.CharField(blank=True, max_length=50)),
                ('short_name', models.CharField(blank=True, max_length=20)),
                ('color', models.CharField(blank=True, help_text='Color hex, p. ej. #4CAF50.', max_length=7)),
                ('multiplier', models.DecimalField(decimal_places=1, default=1, help_text='Ponderador de la ventana: los puntos se multiplican por este factor (1, 1.5, 2 … hasta 10).', max_digits=3)),
                ('opens_at', models.DateTimeField(blank=True, null=True)),
                ('send_deadline', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'ventana',
                'verbose_name_plural': 'ventanas',
                'ordering': ['quiniela', 'order'],
            },
        ),
        migrations.CreateModel(
            name='WindowUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'estado de ventana por usuario',
                'verbose_name_plural': 'estados de ventana por usuario',
            },
        ),
        migrations.RemoveConstraint(
            model_name='prediction',
            name='uq_prediction_user_match',
        ),
        migrations.RemoveConstraint(
            model_name='scoresnapshot',
            name='uq_snapshot_user_match',
        ),
        migrations.AddField(
            model_name='prediction',
            name='quiniela',
            field=models.ForeignKey(blank=True, help_text='Quiniela a la que pertenece el pronóstico (1a: nullable hasta el backfill; luego no-nulo).', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='predictions', to='pool.quiniela'),
        ),
        migrations.AddField(
            model_name='scoresnapshot',
            name='quiniela',
            field=models.ForeignKey(blank=True, help_text='Quiniela del acumulado (1a: nullable hasta backfill).', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='snapshots', to='pool.quiniela'),
        ),
        migrations.AddConstraint(
            model_name='prediction',
            constraint=models.UniqueConstraint(fields=('user', 'match', 'quiniela'), name='uq_prediction_user_match_quiniela'),
        ),
        migrations.AddConstraint(
            model_name='scoresnapshot',
            constraint=models.UniqueConstraint(fields=('user', 'match', 'quiniela'), name='uq_snapshot_user_match_quiniela'),
        ),
        migrations.AddField(
            model_name='userquiniela',
            name='quiniela',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='pool.quiniela'),
        ),
        migrations.AddField(
            model_name='userquiniela',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quiniela_memberships', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='window',
            name='quiniela',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='windows', to='pool.quiniela'),
        ),
        migrations.AddField(
            model_name='window',
            name='stages',
            field=models.ManyToManyField(related_name='windows', to='tournament.stage'),
        ),
        migrations.AddField(
            model_name='windowuser',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='window_states', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='windowuser',
            name='window',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='user_states', to='pool.window'),
        ),
        migrations.AddConstraint(
            model_name='userquiniela',
            constraint=models.UniqueConstraint(fields=('user', 'quiniela'), name='uq_userquiniela_user_quiniela'),
        ),
        migrations.AddConstraint(
            model_name='window',
            constraint=models.UniqueConstraint(fields=('quiniela', 'order'), name='uq_window_quiniela_order'),
        ),
        migrations.AddConstraint(
            model_name='windowuser',
            constraint=models.UniqueConstraint(fields=('user', 'window'), name='uq_windowuser_user_window'),
        ),
    ]
