# Generated by Django 5.2.15 on 2026-06-25 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pool', '0009_userquiniela_window_windowuser_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiniela',
            name='theme',
            field=models.CharField(choices=[('sanginiela', 'Sanginiela — azul marino + oro'), ('medianoche', 'Medianoche — azul profundo + champaña'), ('bienestar', 'Bienestar — guinda (gobierno federal)'), ('bosque', 'Bosque — esmeralda'), ('violeta', 'Violeta — ciruela')], default='sanginiela', help_text='Paleta de color con la que se pinta la quiniela.', max_length=20),
        ),
    ]
