# Generated by Django 5.2.15 on 2026-06-26 04:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pool', '0010_quiniela_theme'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stageuser',
            name='stage',
        ),
        migrations.RemoveField(
            model_name='stageuser',
            name='user',
        ),
        migrations.RemoveConstraint(
            model_name='quiniela',
            name='uq_quiniela_single_default',
        ),
        migrations.RemoveField(
            model_name='quiniela',
            name='is_default',
        ),
        migrations.RemoveField(
            model_name='user',
            name='authorized',
        ),
        migrations.AlterField(
            model_name='prediction',
            name='points',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='Puntos finales ya × Window.multiplier', max_digits=4, null=True),
        ),
        migrations.AlterField(
            model_name='prediction',
            name='quiniela',
            field=models.ForeignKey(help_text='Quiniela a la que pertenece el pronóstico.', on_delete=django.db.models.deletion.CASCADE, related_name='predictions', to='pool.quiniela'),
        ),
        migrations.AlterField(
            model_name='scoresnapshot',
            name='quiniela',
            field=models.ForeignKey(help_text='Quiniela del acumulado.', on_delete=django.db.models.deletion.CASCADE, related_name='snapshots', to='pool.quiniela'),
        ),
        migrations.DeleteModel(
            name='StageUser',
        ),
    ]
