# Generated by Django 5.2.15 on 2026-07-04 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pool', '0012_userquiniela_history_compare'),
    ]

    operations = [
        migrations.AddField(
            model_name='window',
            name='third_place_multiplier',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='Ponderador del partido por el tercer lugar; vacío = usa el multiplicador de la ventana.', max_digits=3, null=True),
        ),
    ]
