# Generated by Django 5.2.15 on 2026-07-08 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pool', '0013_window_third_place_multiplier'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scoresnapshot',
            name='position',
        ),
    ]
